---
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/balena-preload
      publish: true

npm:
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
      node_versions:
        - "10"
        - "12"
