---
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/balena-preload
      publish: true
      platforms: [linux/amd64,linux/arm64,linux/arm/7,linux/arm/6]

npm:
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
      node_versions:
        - "10"
        - "12"
